<?php

namespace Modules\Academic\Entities;

use Illuminate\Database\Eloquent\Model;

class AcaCertificateParameter extends Model
{
    protected $table = 'aca_certificates_parameters';

    protected $fillable = [
        'course_id',
        'certificate_img',
        'certificate_img_width',
        'certificate_img_height',
        'fontfamily_date',
        'font_align_date',
        'font_vertical_align_date',
        'position_date_x',
        'position_date_y',
        'font_size_date',
        'color_date',
        'visible_date',
        'fontfamily_names',
        'font_align_names',
        'font_vertical_align_names',
        'position_names_x',
        'position_names_y',
        'font_size_names',
        'color_names',
        'visible_names',
        'fontfamily_title',
        'font_align_title',
        'font_vertical_align_title',
        'position_title_x',
        'position_title_y',
        'font_size_title',
        'max_width_title',
        'color_title',
        'visible_title',
        'position_qr_x',
        'position_qr_y',
        'size_qr',
        'font_align_qr',
        'visible_image_qr',
        'fontfamily_description',
        'font_align_description',
        'font_vertical_align_description',
        'position_description_x',
        'position_description_y',
        'font_size_description',
        'max_width_description',
        'text_align_description',
        'color_description',
        'visible_description',
        'interspace_description',
        'name_certificate',
        'state',
        'certificate_img_finished',
        'back_certificate_img_finished',
        'for_module',
        'back_certificate_img',
        'back_certificate_img_width',
        'back_certificate_img_height',
        'has_reverse',
        'back_description',
        'back_content_show_manual',
        'back_content_show_course',
        'back_content_show_module',
        'back_content_type',
        'back_content_type_module',
        // Configuración reverso - fecha
        'back_fontfamily_date',
        'back_font_align_date',
        'back_font_vertical_align_date',
        'back_position_date_x',
        'back_position_date_y',
        'back_font_size_date',
        'back_color_date',
        'back_visible_date',
        // Configuración reverso - nombres
        'back_fontfamily_names',
        'back_font_align_names',
        'back_font_vertical_align_names',
        'back_position_names_x',
        'back_position_names_y',
        'back_font_size_names',
        'back_color_names',
        'back_visible_names',
        // Configuración reverso - título
        'back_fontfamily_title',
        'back_font_align_title',
        'back_font_vertical_align_title',
        'back_position_title_x',
        'back_position_title_y',
        'back_font_size_title',
        'back_max_width_title',
        'back_color_title',
        'back_visible_title',
        // Configuración reverso - descripción
        'back_fontfamily_description',
        'back_font_align_description',
        'back_font_vertical_align_description',
        'back_position_description_x',
        'back_position_description_y',
        'back_font_size_description',
        'back_max_width_description',
        'back_text_align_description',
        'back_color_description',
        'back_visible_description',
        // Contenido del curso para reverso
        'back_fontfamily_course',
        'back_font_align_course',
        'back_font_vertical_align_course',
        'back_position_course_x',
        'back_position_course_y',
        'back_font_size_course',
        'back_max_width_course',
        'back_color_course',
        'back_visible_course',
        // Contenido del módulo para reverso
        'back_fontfamily_module',
        'back_font_align_module',
        'back_font_vertical_align_module',
        'back_position_module_x',
        'back_position_module_y',
        'back_font_size_module',
        'back_max_width_module',
        'back_color_module',
        'back_visible_module',
        // QR del reverso
        'back_size_qr',
        'back_font_align_qr',
        'back_position_qr_x',
        'back_position_qr_y',
        'back_visible_qr',
        // Nota Final (PROMEDIO FINAL)
        'back_fontfamily_grade',
        'back_font_size_grade',
        'back_color_grade',
        'back_position_grade_x',
        'back_position_grade_y',
        'back_visible_grade',
        'back_rectangle_width',
        'back_rectangle_height',
        'back_rectangle_color',
    ];

    public function course()
    {
        return $this->belongsTo(AcaCourse::class, 'course_id');
    }
}
