<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    /**
     * Catalogo de profesiones solicitado para el formulario publico de negociacion.
     *
     * Son carreras y especialidades (incluidas las tecnicas). Los que ya existan
     * en el catalogo original de professions se saltan solos: la comparacion es
     * por descripcion normalizada, asi que "Contabilidad" o "Derecho" no se
     * duplican aunque cambie la capitalizacion.
     */
    private const DESCRIPTIONS = [
        'Accounting',
        'Actuaría',
        'Acuicultura',
        'Administración de Empresas',
        'Administración de Negocios Internacionales',
        'Administración Educativa',
        'Administración en Salud',
        'Administración Financiera',
        'Administración Hotelera',
        'Administración Pública',
        'Administración y Dirección de Empresas',
        'Agricultura de Precisión',
        'Agroecología',
        'Agroindustria',
        'Agronomía',
        'Analítica de Datos',
        'Anatomía Patológica',
        'Anestesiología',
        'Animación',
        'Antropología',
        'Architecture',
        'Archivística',
        'Arqueología',
        'Arquitectura',
        'Arquitectura de Software',
        'Arquitectura del Paisaje',
        'Arte Digital',
        'Artes Culinarias',
        'Artes Plásticas',
        'Artes Visuales',
        'Astrofísica',
        'Astronomía',
        'Audiología',
        'Auditoría',
        'Aviación Comercial',
        'Banca y Finanzas',
        'Bellas Artes',
        'Bibliotecología',
        'Bioinformática',
        'Biological Sciences',
        'Biología',
        'Biología Marina',
        'Biología Molecular',
        'Bioquímica',
        'Biotecnología',
        'Botánica',
        'Business Administration',
        'Cardiología',
        'Chemistry',
        'Ciberseguridad',
        'Ciencia Animal',
        'Ciencia de Datos',
        'Ciencia de los Alimentos',
        'Ciencia del Suelo',
        'Ciencia Política',
        'Ciencias Agrarias',
        'Ciencias Ambientales',
        'Ciencias Biomédicas',
        'Ciencias de la Computación',
        'Ciencias de la Educación',
        'Ciencias de la Familia',
        'Ciencias de la Información',
        'Ciencias de la Salud',
        'Ciencias de la Tierra',
        'Ciencias del Deporte',
        'Ciencias del Mar',
        'Ciencias Forestales',
        'Ciencias Jurídicas',
        'Cinematografía',
        'Cirugía General',
        'Comercio Exterior',
        'Computación',
        'Computación en la Nube',
        'Computación Gráfica',
        'Computación Paralela',
        'Computación Teórica',
        'Comunicación',
        'Composición Musical',
        'Construcción',
        'Conservación de Bosques',
        'Conservación y Restauración',
        'Contabilidad',
        'Contaduría Pública',
        'Criminalística',
        'Criminología',
        'Culinary Arts',
        'Danza',
        'Demografía',
        'Dental Medicine',
        'Dentistry',
        'Deportes',
        'Derecho',
        'Derecho Administrativo',
        'Derecho Ambiental',
        'Derecho Civil',
        'Derecho Comercial',
        'Derecho Constitucional',
        'Derecho Corporativo',
        'Derecho de Familia',
        'Derecho Digital',
        'Derecho Empresarial',
        'Derecho Internacional',
        'Derecho Internacional Privado',
        'Derecho Internacional Público',
        'Derecho Laboral',
        'Derecho Penal',
        'Derecho Procesal',
        'Derecho Tributario',
        'Desarrollo de Aplicaciones',
        'Desarrollo de Software',
        'Desarrollo de Videojuegos',
        'Desarrollo Internacional',
        'Desarrollo Social',
        'Dermatología',
        'DevOps',
        'Dietética',
        'Diseño Curricular',
        'Diseño de Interiores',
        'Diseño de Modas',
        'Diseño de Producto',
        'Diseño Gráfico',
        'Diseño Industrial',
        'Diseño Urbano',
        'Ecología',
        'Economics',
        'Economía',
        'Economía Agraria',
        'Economía Aplicada',
        'Economía Social',
        'Edificación',
        'Educación Artística',
        'Educación de Adultos',
        'Educación en Ciencias Naturales',
        'Educación en Lenguas Extranjeras',
        'Educación Especial',
        'Educación Física',
        'Educación Física y Deporte',
        'Educación Inicial',
        'Educación Intercultural Bilingüe',
        'Educación Matemática',
        'Educación Musical',
        'Educación Primaria',
        'Educación Religiosa',
        'Educación Secundaria',
        'Educación Tecnológica',
        'Emprendimiento',
        'Enfermería',
        'Endocrinología',
        'Epidemiología',
        'Estadística',
        'Estomatología',
        'Estudios Clásicos',
        'Estudios Culturales',
        'Estudios de Género',
        'Estudios de Paz y Conflictos',
        'Estudios Urbanos',
        'Extensión Agraria',
        'Farmacia',
        'Filología',
        'Filosofía',
        'Finanzas',
        'Física',
        'Física Aplicada',
        'Fisioterapia',
        'Fitotecnia',
        'Fonoaudiología',
        'Fotografía',
        'Gastroenterología',
        'Gastronomía',
        'Genética',
        'Genética Médica',
        'Geofísica',
        'Geografía',
        'Geología',
        'Geriatría',
        'Gerontología',
        'Gerontología Social',
        'Gestión Aeroportuaria',
        'Gestión Comercial',
        'Gestión Cultural',
        'Gestión de Emergencias',
        'Gestión de Emprendimiento',
        'Gestión de Eventos',
        'Gestión de Innovación',
        'Gestión de la Cadena de Suministro',
        'Gestión de la Calidad',
        'Gestión de Marketing',
        'Gestión de Operaciones',
        'Gestión de Proyectos',
        'Gestión de Recursos Humanos',
        'Gestión de Riesgos y Desastres',
        'Gestión de Servicios de Salud',
        'Gestión del Talento',
        'Gestión Educativa',
        'Gestión Empresarial',
        'Gestión Estratégica',
        'Gestión Portuaria',
        'Gestión Tributaria',
        'Gestión Turística',
        'Hematología',
        'Higiene Ocupacional',
        'Historia',
        'Historia del Arte',
        'Horticultura',
        'Hotelería',
        'Ilustración',
        'Imagenología',
        'Infectología',
        'Informática',
        'Informática Biomédica',
        'Ingeniería Aeroespacial',
        'Ingeniería Aeronáutica',
        'Ingeniería Agrícola',
        'Ingeniería Agroindustrial',
        'Ingeniería Agronómica',
        'Ingeniería Ambiental',
        'Ingeniería Automotriz',
        'Ingeniería Biomédica',
        'Ingeniería Civil',
        'Ingeniería de Alimentos',
        'Ingeniería de Calidad de Software',
        'Ingeniería de Computación',
        'Ingeniería de Datos',
        'Ingeniería de Gas',
        'Ingeniería de Mantenimiento',
        'Ingeniería de Manufactura',
        'Ingeniería de Materiales',
        'Ingeniería de Minas',
        'Ingeniería de Petróleo',
        'Ingeniería de Procesos',
        'Ingeniería de Producción',
        'Ingeniería de Recursos Hídricos',
        'Ingeniería de Seguridad',
        'Ingeniería de Sistemas',
        'Ingeniería de Sistemas de Información',
        'Ingeniería de Software',
        'Ingeniería de Software Empresarial',
        'Ingeniería de Telecomunicaciones',
        'Ingeniería de Transportes',
        'Ingeniería Eléctrica',
        'Ingeniería Electrónica',
        'Ingeniería en Desarrollo de Software',
        'Ingeniería en Telecomunicaciones',
        'Ingeniería Energética',
        'Ingeniería Estructural',
        'Ingeniería Ferroviaria',
        'Ingeniería Forestal',
        'Ingeniería Geomática',
        'Ingeniería Geotécnica',
        'Ingeniería Hidráulica',
        'Ingeniería Industrial',
        'Ingeniería Informática',
        'Ingeniería Marítima',
        'Ingeniería Mecánica',
        'Ingeniería Mecatrónica',
        'Ingeniería Metalúrgica',
        'Ingeniería Naval',
        'Ingeniería Nuclear',
        'Ingeniería Pesquera',
        'Ingeniería Petroquímica',
        'Ingeniería Química',
        'Ingeniería Sanitaria',
        'Ingeniería Telemática',
        'Ingeniería Topográfica',
        'Ingeniería Vial',
        'Ingeniería Web',
        'Inteligencia Artificial',
        'Interacción Humano-Computadora',
        'Laboratorio Clínico',
        'Law',
        'Lenguas Modernas',
        'Lingüística',
        'Literatura',
        'Logística',
        'Logopedia',
        'Manejo Forestal',
        'Marketing',
        'Marketing Digital',
        'Matemática Aplicada',
        'Matemáticas',
        'Mathematics',
        'Medicina',
        'Medicina de Emergencias',
        'Medicina Familiar',
        'Medicina General',
        'Medicina Humana',
        'Medicina Interna',
        'Medicina Tradicional y Complementaria',
        'Medicina Veterinaria',
        'Medicine',
        'Mercadotecnia',
        'Meteorología',
        'Microbiología',
        'Musicología',
        'Música',
        'Nanotecnología',
        'Náutica',
        'Negocios Internacionales',
        'Neurología',
        'Notariado y Registro',
        'Nursing',
        'Nutrición',
        'Obstetricia',
        'Oceanografía',
        'Odontología',
        'Oftalmología',
        'Oncología',
        'Optometría',
        'Orientación Educativa',
        'Paleontología',
        'Patrimonio Cultural',
        'Pedagogía',
        'Pediatría',
        'Periodismo',
        'Physics',
        'Podología',
        'Prevención de Riesgos Laborales',
        'Producción Agropecuaria',
        'Producción Animal',
        'Propiedad Intelectual',
        'Protección Civil',
        'Psicología',
        'Psicología Clínica',
        'Psicopedagogía',
        'Psiquiatría',
        'Psychology',
        'Publicidad',
        'Química',
        'Química Farmacéutica',
        'Química Industrial',
        'Radiología',
        'Radioterapia',
        'Realidad Virtual y Aumentada',
        'Recreación',
        'Redes y Telecomunicaciones',
        'Rehabilitación',
        'Relaciones Internacionales',
        'Relaciones Públicas',
        'Religiones Comparadas',
        'Robótica',
        'Salud Ambiental',
        'Salud Ocupacional',
        'Salud Pública',
        'Seguridad Industrial',
        'Seguridad Informática',
        'Seguridad Integral',
        'Seguridad y Defensa',
        'Seguros',
        'Servicios Comunitarios',
        'Silvicultura',
        'Sistemas de Información',
        'Sistemas Distribuidos',
        'Sistemas Embebidos',
        'Sociología',
        'Software Engineering',
        'Supply Chain Management',
        'Systems Engineering',
        'Técnico Aeronáutico',
        'Técnico Agrícola',
        'Técnico Agropecuario',
        'Técnico Automotriz de Diagnóstico Electrónico',
        'Técnico Deportivo',
        'Técnico Dental',
        'Técnico Electricista',
        'Técnico Electrónico',
        'Técnico en 3D y Modelado Digital',
        'Técnico en Acuicultura',
        'Técnico en Administración',
        'Técnico en Administración de Empresas',
        'Técnico en Administración Pública',
        'Técnico en Agencias de Viajes',
        'Técnico en Agricultura de Precisión',
        'Técnico en Agroecología',
        'Técnico en Agroindustria',
        'Técnico en Agronegocios',
        'Técnico en Alimentos',
        'Técnico en Almacenes',
        'Técnico en Anatomía Patológica',
        'Técnico en Análisis Químico',
        'Técnico en Animación Digital',
        'Técnico en Aplicaciones Móviles',
        'Técnico en Archivística',
        'Técnico en Artes Gráficas',
        'Técnico en Asistencia Legal',
        'Técnico en Atención Prehospitalaria',
        'Técnico en Audiología',
        'Técnico en Automatización',
        'Técnico en Automatización Industrial',
        'Técnico en Auxiliar de Educación',
        'Técnico en Banca',
        'Técnico en Bartender y Coctelería',
        'Técnico en Base de Datos',
        'Técnico en Bibliotecología',
        'Técnico en Calidad Industrial',
        'Técnico en Ciberseguridad',
        'Técnico en Ciencia de Datos',
        'Técnico en CNC',
        'Técnico en Cocina',
        'Técnico en Comercio Exterior',
        'Técnico en Compras',
        'Técnico en Comunicación Audiovisual',
        'Técnico en Computación',
        'Técnico en Computación en la Nube',
        'Técnico en Confecciones',
        'Técnico en Conservación de Recursos Naturales',
        'Técnico en Conservación y Restauración',
        'Técnico en Construcción Civil',
        'Técnico en Contabilidad',
        'Técnico en Control de Calidad',
        'Técnico en Control Industrial',
        'Técnico en Criminalística',
        'Técnico en Defensa Civil',
        'Técnico en Desarrollo de Software',
        'Técnico en Desarrollo Web',
        'Técnico en Dibujo Técnico',
        'Técnico en Diseño CAD',
        'Técnico en Diseño de Interiores',
        'Técnico en Diseño de Modas',
        'Técnico en Diseño Gráfico',
        'Técnico en Edificaciones',
        'Técnico en Educación Especial',
        'Técnico en Educación Física',
        'Técnico en Educación Inicial',
        'Técnico en Educación Primaria',
        'Técnico en Electrónica Digital',
        'Técnico en Emergencias Médicas',
        'Técnico en Energía Eléctrica',
        'Técnico en Energías Renovables',
        'Técnico en Enfermería',
        'Técnico en Enfermería Técnica',
        'Técnico en Enfermería Veterinaria',
        'Técnico en Entrenamiento Deportivo',
        'Técnico en Estadística',
        'Técnico en Farmacia',
        'Técnico en Finanzas',
        'Técnico en Fisioterapia',
        'Técnico en Fotografía',
        'Técnico en Gastronomía',
        'Técnico en Geología',
        'Técnico en Geomática',
        'Técnico en Gestión Ambiental',
        'Técnico en Gestión de Proyectos',
        'Técnico en Gestión de Riesgos',
        'Técnico en Gestión Documental',
        'Técnico en Gestión Empresarial',
        'Técnico en Gestión Hotelera',
        'Técnico en Guía de Turismo',
        'Técnico en Hemoterapia',
        'Técnico en Higiene Dental',
        'Técnico en Histología',
        'Técnico en Horticultura',
        'Técnico en Hotelería',
        'Técnico en Ilustración',
        'Técnico en Imagenología',
        'Técnico en Informática',
        'Técnico en Instalaciones Eléctricas',
        'Técnico en Instalaciones Sanitarias',
        'Técnico en Instrumentación Industrial',
        'Técnico en Instrumentación Quirúrgica',
        'Técnico en Inteligencia Artificial',
        'Técnico en Laboratorio',
        'Técnico en Laboratorio Biológico',
        'Técnico en Laboratorio Clínico',
        'Técnico en Laboratorio Químico',
        'Técnico en Logística',
        'Técnico en Manejo de Bosques',
        'Técnico en Mantenimiento Aeronáutico',
        'Técnico en Mantenimiento de Aeronaves',
        'Técnico en Mantenimiento Electromecánico',
        'Técnico en Mantenimiento Industrial',
        'Técnico en Manufactura',
        'Técnico en Marketing',
        'Técnico en Mecánica Automotriz',
        'Técnico en Mecánica Industrial',
        'Técnico en Mecatrónica',
        'Técnico en Medio Ambiente',
        'Técnico en Metalurgia',
        'Técnico en Meteorología',
        'Técnico en Minería',
        'Técnico en Multimedia',
        'Técnico en Negocios Internacionales',
        'Técnico en Nutrición',
        'Técnico en Obras Viales',
        'Técnico en Odontología',
        'Técnico en Operaciones Aeroportuarias',
        'Técnico en Operaciones Portuarias',
        'Técnico en Organización de Eventos',
        'Técnico en Panadería',
        'Técnico en Pastelería',
        'Técnico en Periodismo',
        'Técnico en Petroquímica',
        'Técnico en Petróleo y Gas',
        'Técnico en Podología',
        'Técnico en Prevención de Riesgos',
        'Técnico en Procesamiento de Minerales',
        'Técnico en Procesamiento Pesquero',
        'Técnico en Procesos Industriales',
        'Técnico en Producción Agrícola',
        'Técnico en Producción Animal',
        'Técnico en Producción Audiovisual',
        'Técnico en Producción de Medios',
        'Técnico en Producción Industrial',
        'Técnico en Producción Musical',
        'Técnico en Programación',
        'Técnico en Prótesis Dental',
        'Técnico en Química Industrial',
        'Técnico en Radiología',
        'Técnico en Radioterapia',
        'Técnico en Recursos Humanos',
        'Técnico en Recreación',
        'Técnico en Redes',
        'Técnico en Refrigeración y Climatización',
        'Técnico en Rehabilitación',
        'Técnico en Relaciones Públicas',
        'Técnico en Riego',
        'Técnico en Robótica',
        'Técnico en Salud Ocupacional',
        'Técnico en Salud Pública',
        'Técnico en Seguridad',
        'Técnico en Seguridad Ciudadana',
        'Técnico en Seguridad Industrial',
        'Técnico en Seguridad Informática',
        'Técnico en Seguridad Privada',
        'Técnico en Seguridad y Salud en el Trabajo',
        'Técnico en Seguros',
        'Técnico en Silvicultura',
        'Técnico en Sistemas',
        'Técnico en Sistemas Embebidos',
        'Técnico en Soldadura',
        'Técnico en Sonido',
        'Técnico en Soporte Informático',
        'Técnico en Suelos',
        'Técnico en Teatro',
        'Técnico en Tecnología de Alimentos',
        'Técnico en Telecomunicaciones',
        'Técnico en Terapia Ocupacional',
        'Técnico en Topografía',
        'Técnico en Trabajo Social',
        'Técnico en Transporte',
        'Técnico en Tributación',
        'Técnico en Turismo',
        'Técnico en Ventas',
        'Técnico en Videojuegos',
        'Técnico en Viveros',
        'Técnico en Zootecnia',
        'Técnico en óptica y Optometría',
        'Técnico Forestal',
        'Técnico Jurídico',
        'Técnico Naval',
        'Técnico Paramédico',
        'Técnico Pecuario',
        'Técnico Pesquero',
        'Técnico Textil',
        'Técnico Veterinario',
        'Tecnología de Alimentos',
        'Tecnología Educativa',
        'Tecnología Médica',
        'Tecnologías de la Información',
        'Teatro',
        'Terapia del Lenguaje',
        'Terapia Física',
        'Terapia Ocupacional',
        'Tourism Management',
        'Trabajo Social',
        'Traducción e Interpretación',
        'Transporte y Logística',
        'Traumatología y Ortopedia',
        'Turismo',
        'Urbanismo',
        'Urología',
        'Veterinaria',
        'Visión por Computador',
        'Zootecnia',
        'Zoología',
        'óptica',
    ];

    /**
     * Descripciones que ya existian en el catalogo original de professions.
     *
     * Sirve para que el down() no borre filas que no creo esta migracion (son las
     * unicas que coinciden textualmente con el catalogo original).
     */
    private const PREEXISTING = [
        'Ingeniería de sistemas',
        'Ingeniería industrial',
        'Ingeniería civil',
        'Ingeniería electrónica',
        'Ingeniería mecánica',
        'Ingeniería ambiental',
        'Medicina',
        'Enfermería',
        'Odontología',
        'Contabilidad',
        'Derecho',
        'Psicología',
        'Administración de empresas',
        'Economía',
        'Arquitectura',
        'Educación',
        'Comunicación',
        'Periodismo',
        'Diseño gráfico',
        'Trabajo social',
        'Filosofía',
        'Sociología',
        'Relaciones internacionales',
        'Ciencias políticas',
        'Biología',
        'Química',
        'Física',
        'Matemáticas',
        'Farmacia y bioquímica',
        'Turismo y hotelería',
        'Gastronomía',
        'Veterinaria',
        'Sin especificar',
        'Otros',
    ];

    /**
     * Desde que id empiezan los codigos reservados del catalogo original
     * ("Sin especificar" = 998, "Otros" = 999). Las profesiones nuevas se
     * numeran por debajo de este limite.
     */
    private const RESERVED_FROM = 998;

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // professions.id es smallint sin autoincremento: los ids se asignan a
        // mano, continuando despues del ultimo id real del catalogo (32).
        $nextId = (int) DB::table('professions')
            ->where('id', '<', self::RESERVED_FROM)
            ->max('id');

        foreach (self::DESCRIPTIONS as $description) {
            if ($this->findId($description)) {
                continue;
            }

            // Defensivo: si el id calculado ya esta ocupado (catalogo ampliado a
            // mano entre migraciones), se busca el primero libre.
            do {
                $nextId++;
            } while (DB::table('professions')->where('id', $nextId)->exists());

            DB::table('professions')->insert([
                'id' => $nextId,
                'description' => $description,
            ]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Solo se quitan las filas que agrego esta migracion, y solo si nadie las
        // usa. Las de PREEXISTING ya estaban con ese mismo texto: no se borran.
        foreach (self::DESCRIPTIONS as $description) {
            if ($this->isPreexisting($description)) {
                continue;
            }

            $id = $this->findId($description);

            if (! $id || DB::table('people')->where('profession_id', $id)->exists()) {
                continue;
            }

            DB::table('professions')->where('id', $id)->delete();
        }
    }

    /**
     * Id de la profesion por descripcion, ignorando mayusculas y espacios.
     *
     * El catalogo original guarda algunas descripciones con distinta
     * capitalizacion ("Administración de empresas"), asi que la comparacion
     * normalizada evita duplicar una profesion que ya existe escrita de otra
     * forma.
     */
    private function findId(string $description): ?int
    {
        $id = DB::table('professions')
            ->whereRaw('LOWER(TRIM(description)) = ?', [Str::lower(trim($description))])
            ->value('id');

        return $id === null ? null : (int) $id;
    }

    /**
     * Indica si la descripcion pertenece al catalogo original (comparacion
     * normalizada, igual que findId).
     */
    private function isPreexisting(string $description): bool
    {
        $normalized = Str::lower(trim($description));

        foreach (self::PREEXISTING as $preexisting) {
            if (Str::lower(trim($preexisting)) === $normalized) {
                return true;
            }
        }

        return false;
    }
};
